.PHONY: all clean

all: 
	pdflatex niveau.tex
	#bibtex   niveau.aux
	pdflatex niveau.tex
	pdflatex niveau.tex
	pdflatex niveau.tex

clean:
	rm -f *.aux
	rm -f *.bbl
	rm -f *.blg
	rm -f *.log
	rm -f *.out
	rm -f *.toc
	rm -f *.lot
	rm -f *.lof

